import type { CafeProfile, MenuCategory, MenuItem, Order } from "./types";

export const demoCafe: CafeProfile = {
  slug: "velvet-bean",
  name: "Velvet Bean Café & Roastery",
  tagline: "House-roasted coffee · all-day brunch",
  accentColor: "#E8B62C",
  hours: "Tue–Sun · 8:00 am – 6:30 pm",
  tableCount: 12,
  cashOnly: true,
  currency: "USD",
  address: "42 Blossom Lane, Corner Bistro Plaza",
};

export const demoCategories: MenuCategory[] = [
  { id: "coffee", name: "Coffee & Drinks", sort: 1 },
  { id: "teas", name: "Artisan Teas", sort: 2 },
  { id: "brunch", name: "All-Day Brunch", sort: 3 },
  { id: "sandwiches", name: "Sandwiches & Bowls", sort: 4 },
  { id: "bakery", name: "Bakery & Pastries", sort: 5 },
];

export const demoItems: MenuItem[] = [
  {
    id: "flat-white",
    categoryId: "coffee",
    name: "Single Origin Flat White",
    description: "Double ristretto, Ethiopian Yirgacheffe, micro-foam milk.",
    price: 4.8,
    prepMinutes: 4,
    tags: ["popular", "veg"],
    image:
      "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80",
    hasMilk: true,
    hasExtraShot: true,
  },
  {
    id: "macchiato",
    categoryId: "coffee",
    name: "Caramel Cloud Macchiato",
    description: "Espresso marked with vanilla cloud foam and a caramel veil.",
    price: 5.5,
    prepMinutes: 5,
    tags: ["popular", "veg"],
    image:
      "https://images.unsplash.com/photo-1485808191679-5f86534bd76f?auto=format&fit=crop&w=900&q=80",
    hasMilk: true,
    hasExtraShot: true,
  },
  {
    id: "nitro",
    categoryId: "coffee",
    name: "Cold Brew Nitro Reserve",
    description: "18-hour steep, nitrogen cascade, served unsweetened.",
    price: 5.2,
    prepMinutes: 2,
    tags: ["vegan", "gf"],
    image:
      "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "matcha",
    categoryId: "teas",
    name: "Ceremonial Iced Matcha Latte",
    description: "Stone-milled Uji matcha, shaken over ice with your milk.",
    price: 5.9,
    prepMinutes: 4,
    tags: ["popular", "veg", "gf"],
    image:
      "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80",
    hasMilk: true,
    hasExtraShot: false,
  },
  {
    id: "chai",
    categoryId: "teas",
    name: "Spiced Golden Chai Infusion",
    description: "Cardamom, ginger, and turmeric steeped to order.",
    price: 4.9,
    prepMinutes: 5,
    tags: ["veg", "gf"],
    image:
      "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80",
    hasMilk: true,
    hasExtraShot: false,
  },
  {
    id: "truffle-toast",
    categoryId: "brunch",
    name: "Truffle Scrambled Brioche Toast",
    description: "Soft eggs, black truffle butter, chives, toasted brioche.",
    price: 13.5,
    prepMinutes: 12,
    tags: ["popular", "veg"],
    image:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "avocado",
    categoryId: "brunch",
    name: "Avocado & Citrus Sourdough Tartine",
    description: "Ripe avocado, grapefruit, chili flake, house sourdough.",
    price: 11.9,
    prepMinutes: 8,
    tags: ["veg"],
    image:
      "https://images.unsplash.com/photo-1541519227354-08fa9d52bf53?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "pancakes",
    categoryId: "brunch",
    name: "Wild Blueberry Ricotta Pancakes",
    description: "Lemon ricotta batter, blueberry compote, maple.",
    price: 12.8,
    prepMinutes: 14,
    tags: ["popular", "veg"],
    image:
      "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "panini",
    categoryId: "sandwiches",
    name: "Crispy Prosciutto & Pesto Panini",
    description: "Pressed ciabatta, basil pesto, mozzarella, tomato.",
    price: 12.5,
    prepMinutes: 10,
    tags: ["popular"],
    image:
      "https://images.unsplash.com/photo-1539252554453-80da39721045?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "bowl",
    categoryId: "sandwiches",
    name: "Mediterranean Quinoa Glow Bowl",
    description: "Quinoa, cucumber, olives, tahini lemon, herbs.",
    price: 11.5,
    prepMinutes: 7,
    tags: ["veg", "gf"],
    image:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "croissant",
    categoryId: "bakery",
    name: "Almond Frangipane Butter Croissant",
    description: "Laminated butter pastry filled with almond cream.",
    price: 4.75,
    prepMinutes: 3,
    tags: ["popular", "veg"],
    image:
      "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
  {
    id: "babka",
    categoryId: "bakery",
    name: "Salted Dark Chocolate Babka Slice",
    description: "Cocoa swirl loaf, flaky salt, served slightly warm.",
    price: 4.5,
    prepMinutes: 2,
    tags: ["veg"],
    image:
      "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=900&q=80",
    hasMilk: false,
    hasExtraShot: false,
  },
];

export function demoOrders(now = Date.now()): Order[] {
  return [
    {
      id: "VB-2408",
      table: "02",
      guestName: "Asha",
      phone: "",
      notes: "Oat milk on the flat white",
      items: [
        { itemId: "flat-white", name: "Single Origin Flat White", qty: 1, unitPrice: 5.3, milk: "oat" },
        { itemId: "croissant", name: "Almond Frangipane Butter Croissant", qty: 1, unitPrice: 4.75 },
      ],
      subtotal: 10.05,
      tax: 0.8,
      total: 10.85,
      status: "new",
      createdAt: now - 4 * 60000,
      estimatedWait: 4,
      payCash: true,
    },
    {
      id: "VB-2406",
      table: "07",
      guestName: "Guest",
      phone: "",
      notes: "",
      items: [
        { itemId: "pancakes", name: "Wild Blueberry Ricotta Pancakes", qty: 1, unitPrice: 12.8 },
        { itemId: "matcha", name: "Ceremonial Iced Matcha Latte", qty: 1, unitPrice: 5.9, milk: "whole" },
      ],
      subtotal: 18.7,
      tax: 1.5,
      total: 20.2,
      status: "preparing",
      createdAt: now - 11 * 60000,
      estimatedWait: 14,
      payCash: true,
    },
    {
      id: "VB-2403",
      table: "11",
      guestName: "Rohit",
      phone: "98765 43210",
      notes: "No chili on the panini",
      items: [
        { itemId: "panini", name: "Crispy Prosciutto & Pesto Panini", qty: 1, unitPrice: 12.5 },
        { itemId: "nitro", name: "Cold Brew Nitro Reserve", qty: 2, unitPrice: 5.2 },
      ],
      subtotal: 22.9,
      tax: 1.83,
      total: 24.73,
      status: "ready",
      createdAt: now - 18 * 60000,
      estimatedWait: 10,
      payCash: true,
    },
  ];
}
