/** Seed menus for velvet-bean and spice-lane */

const velvetBean = {
  slug: "velvet-bean",
  name: "Velvet Bean Café & Roastery",
  tagline: "House-roasted coffee · all-day brunch",
  accent_color: "#E8B62C",
  hours: "Tue–Sun · 8:00 am – 6:30 pm",
  address: "42 Blossom Lane, Corner Bistro Plaza",
  table_count: 12,
  cash_only: 1,
  currency: "USD",
  country: "US",
  tax_name: "Tax",
  tax_rate: 0.08,
  owner_pin: "1234",
  staff_pin: "1234",
  categories: [
    { id: "vb-coffee", name: "Coffee & Drinks", sort: 1 },
    { id: "vb-teas", name: "Artisan Teas", sort: 2 },
    { id: "vb-brunch", name: "All-Day Brunch", sort: 3 },
    { id: "vb-sandwiches", name: "Sandwiches & Bowls", sort: 4 },
    { id: "vb-bakery", name: "Bakery & Pastries", sort: 5 },
  ],
  items: [
    {
      id: "vb-flat-white",
      category_id: "vb-coffee",
      name: "Single Origin Flat White",
      description: "Double ristretto, Ethiopian Yirgacheffe, micro-foam milk.",
      price: 4.8,
      prep_minutes: 4,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 1,
    },
    {
      id: "vb-macchiato",
      category_id: "vb-coffee",
      name: "Caramel Cloud Macchiato",
      description: "Espresso marked with vanilla cloud foam and a caramel veil.",
      price: 5.5,
      prep_minutes: 5,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1485808191679-5f86534bd76f?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 1,
    },
    {
      id: "vb-nitro",
      category_id: "vb-coffee",
      name: "Cold Brew Nitro Reserve",
      description: "18-hour steep, nitrogen cascade, served unsweetened.",
      price: 5.2,
      prep_minutes: 2,
      tags: ["vegan", "gf"],
      image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-matcha",
      category_id: "vb-teas",
      name: "Ceremonial Iced Matcha Latte",
      description: "Stone-milled Uji matcha, shaken over ice with your milk.",
      price: 5.9,
      prep_minutes: 4,
      tags: ["popular", "veg", "gf"],
      image: "https://images.unsplash.com/photo-1515823064-d6e0c04616a7?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "vb-chai",
      category_id: "vb-teas",
      name: "Spiced Golden Chai Infusion",
      description: "Cardamom, ginger, and turmeric steeped to order.",
      price: 4.9,
      prep_minutes: 5,
      tags: ["veg", "gf"],
      image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "vb-truffle-toast",
      category_id: "vb-brunch",
      name: "Truffle Scrambled Brioche Toast",
      description: "Soft eggs, black truffle butter, chives, toasted brioche.",
      price: 13.5,
      prep_minutes: 12,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-avocado",
      category_id: "vb-brunch",
      name: "Avocado & Citrus Sourdough Tartine",
      description: "Ripe avocado, grapefruit, chili flake, house sourdough.",
      price: 11.9,
      prep_minutes: 8,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1541519227354-08fa9d52bf53?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-pancakes",
      category_id: "vb-brunch",
      name: "Wild Blueberry Ricotta Pancakes",
      description: "Lemon ricotta batter, blueberry compote, maple.",
      price: 12.8,
      prep_minutes: 14,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-panini",
      category_id: "vb-sandwiches",
      name: "Crispy Prosciutto & Pesto Panini",
      description: "Pressed ciabatta, basil pesto, mozzarella, tomato.",
      price: 12.5,
      prep_minutes: 10,
      tags: ["popular"],
      image: "https://images.unsplash.com/photo-1539252554453-80da39721045?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-bowl",
      category_id: "vb-sandwiches",
      name: "Mediterranean Quinoa Glow Bowl",
      description: "Quinoa, cucumber, olives, tahini lemon, herbs.",
      price: 11.5,
      prep_minutes: 7,
      tags: ["veg", "gf"],
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-croissant",
      category_id: "vb-bakery",
      name: "Almond Frangipane Butter Croissant",
      description: "Laminated butter pastry filled with almond cream.",
      price: 4.75,
      prep_minutes: 3,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "vb-babka",
      category_id: "vb-bakery",
      name: "Salted Dark Chocolate Babka Slice",
      description: "Cocoa swirl loaf, flaky salt, served slightly warm.",
      price: 4.5,
      prep_minutes: 2,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
  ],
  demoOrders: (cafeId, now) => [
    {
      id: "VB-2408",
      cafe_id: cafeId,
      table_no: "02",
      guest_name: "Asha",
      phone: "",
      notes: "Oat milk on the flat white",
      items: [
        { itemId: "vb-flat-white", name: "Single Origin Flat White", qty: 1, unitPrice: 5.3, milk: "oat" },
        { itemId: "vb-croissant", name: "Almond Frangipane Butter Croissant", qty: 1, unitPrice: 4.75 },
      ],
      subtotal: 10.05,
      tax: 0.8,
      tax_name: "Tax",
      total: 10.85,
      status: "new",
      estimated_wait: 4,
      confirm_code: "4821",
      dining_option: "dine_in",
      created_at: now - 4 * 60000,
      updated_at: now - 4 * 60000,
    },
    {
      id: "VB-2406",
      cafe_id: cafeId,
      table_no: "07",
      guest_name: "Guest",
      phone: "",
      notes: "",
      items: [
        { itemId: "vb-pancakes", name: "Wild Blueberry Ricotta Pancakes", qty: 1, unitPrice: 12.8 },
        { itemId: "vb-matcha", name: "Ceremonial Iced Matcha Latte", qty: 1, unitPrice: 5.9, milk: "whole" },
      ],
      subtotal: 18.7,
      tax: 1.5,
      tax_name: "Tax",
      total: 20.2,
      status: "preparing",
      estimated_wait: 14,
      confirm_code: "3910",
      dining_option: "dine_in",
      created_at: now - 11 * 60000,
      updated_at: now - 11 * 60000,
    },
    {
      id: "VB-2403",
      cafe_id: cafeId,
      table_no: "11",
      guest_name: "Rohit",
      phone: "98765 43210",
      notes: "No chili on the panini",
      items: [
        { itemId: "vb-panini", name: "Crispy Prosciutto & Pesto Panini", qty: 1, unitPrice: 12.5 },
        { itemId: "vb-nitro", name: "Cold Brew Nitro Reserve", qty: 2, unitPrice: 5.2 },
      ],
      subtotal: 22.9,
      tax: 1.83,
      tax_name: "Tax",
      total: 24.73,
      status: "ready",
      estimated_wait: 10,
      confirm_code: "7742",
      dining_option: "takeaway",
      created_at: now - 18 * 60000,
      updated_at: now - 18 * 60000,
    },
  ],
};

const spiceLane = {
  slug: "spice-lane",
  name: "Spice Lane Chai & Snacks",
  tagline: "Masala chai · street snacks · all day",
  accent_color: "#B85C38",
  hours: "Mon–Sat · 7:30 am – 9:00 pm",
  address: "18 Market Road, Old Town",
  table_count: 8,
  cash_only: 1,
  currency: "INR",
  country: "IN",
  tax_name: "GST",
  tax_rate: 0.05,
  owner_pin: "1234",
  staff_pin: "1234",
  categories: [
    { id: "sl-drinks", name: "Chai & Drinks", sort: 1 },
    { id: "sl-snacks", name: "Snacks", sort: 2 },
    { id: "sl-sweets", name: "Sweets", sort: 3 },
  ],
  items: [
    {
      id: "sl-masala-chai",
      category_id: "sl-drinks",
      name: "Masala Chai (Cutting)",
      description: "Fresh ginger, cardamom, strong Assam, boiled with milk.",
      price: 40,
      prep_minutes: 5,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "sl-filter-coffee",
      category_id: "sl-drinks",
      name: "South Indian Filter Coffee",
      description: "Decoction poured over hot milk, frothed in a davara.",
      price: 60,
      prep_minutes: 4,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "sl-lassi",
      category_id: "sl-drinks",
      name: "Sweet Mango Lassi",
      description: "Hung curd, Alphonso pulp, a pinch of cardamom.",
      price: 90,
      prep_minutes: 3,
      tags: ["veg", "gf"],
      image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "sl-samosa",
      category_id: "sl-snacks",
      name: "Aloo Samosa (2 pcs)",
      description: "Crispy pastry, spiced potato filling, mint chutney.",
      price: 50,
      prep_minutes: 6,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "sl-vada-pav",
      category_id: "sl-snacks",
      name: "Vada Pav",
      description: "Batata vada, soft pav, green chutney, dry garlic.",
      price: 45,
      prep_minutes: 8,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1606491956689-2ea866880067?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "sl-pav-bhaji",
      category_id: "sl-snacks",
      name: "Butter Pav Bhaji",
      description: "Mashed veg curry, buttered pav, onion & lemon.",
      price: 120,
      prep_minutes: 12,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
      available: 0,
    },
    {
      id: "sl-jalebi",
      category_id: "sl-sweets",
      name: "Hot Jalebi (plate)",
      description: "Crisp saffron syrup coils, served warm.",
      price: 70,
      prep_minutes: 5,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
  ],
  demoOrders: (cafeId, now) => [
    {
      id: "SL-1012",
      cafe_id: cafeId,
      table_no: "03",
      guest_name: "Priya",
      phone: "",
      notes: "Less sugar in chai",
      items: [
        { itemId: "sl-masala-chai", name: "Masala Chai (Cutting)", qty: 2, unitPrice: 40 },
        { itemId: "sl-samosa", name: "Aloo Samosa (2 pcs)", qty: 1, unitPrice: 50 },
      ],
      subtotal: 130,
      tax: 6.5,
      tax_name: "GST",
      total: 136.5,
      status: "new",
      estimated_wait: 6,
      confirm_code: "5503",
      dining_option: "dine_in",
      created_at: now - 3 * 60000,
      updated_at: now - 3 * 60000,
    },
  ],
};


const himalayanBeans = {
  slug: "himalayan-beans",
  name: "Himalayan Beans Café",
  tagline: "Chiya · momo · mountain roast",
  accent_color: "#1B6B4A",
  hours: "Daily · 7:00 am – 8:00 pm",
  address: "Thamel Marg, Kathmandu",
  table_count: 10,
  cash_only: 1,
  currency: "NPR",
  country: "NP",
  tax_name: "VAT",
  tax_rate: 0.13,
  owner_pin: "1234",
  staff_pin: "1234",
  categories: [
    { id: "hb-drinks", name: "Chiya & Coffee", sort: 1 },
    { id: "hb-eats", name: "Khaja & Momo", sort: 2 },
    { id: "hb-sweets", name: "Sweets", sort: 3 },
  ],
  items: [
    {
      id: "hb-chiya",
      category_id: "hb-drinks",
      name: "Masala Chiya",
      description: "Spiced milk tea, boiled strong — Kathmandu classic.",
      price: 80,
      prep_minutes: 5,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "hb-filter",
      category_id: "hb-drinks",
      name: "Himalayan Filter Coffee",
      description: "Local roast, poured over hot milk.",
      price: 120,
      prep_minutes: 4,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=80",
      has_milk: 1,
      has_extra_shot: 0,
    },
    {
      id: "hb-lassi",
      category_id: "hb-drinks",
      name: "Sweet Lassi",
      description: "Yogurt shake with a pinch of cardamom.",
      price: 150,
      prep_minutes: 3,
      tags: ["veg", "gf"],
      image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "hb-momo",
      category_id: "hb-eats",
      name: "Chicken Momo (10 pcs)",
      description: "Steamed dumplings with tomato achar.",
      price: 250,
      prep_minutes: 15,
      tags: ["popular"],
      image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "hb-veg-momo",
      category_id: "hb-eats",
      name: "Veg Momo (10 pcs)",
      description: "Cabbage, carrot, and spice mix — steamed.",
      price: 220,
      prep_minutes: 15,
      tags: ["popular", "veg"],
      image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "hb-chowmein",
      category_id: "hb-eats",
      name: "Veg Chowmein",
      description: "Wok noodles, seasonal veg, light soy.",
      price: 180,
      prep_minutes: 12,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
    {
      id: "hb-sel",
      category_id: "hb-sweets",
      name: "Sel Roti (2 pcs)",
      description: "Crisp rice-flour rings, lightly sweet.",
      price: 60,
      prep_minutes: 5,
      tags: ["veg"],
      image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80",
      has_milk: 0,
      has_extra_shot: 0,
    },
  ],
  demoOrders: (cafeId, now) => [
    {
      id: "HB-3011",
      cafe_id: cafeId,
      table_no: "04",
      guest_name: "Sita",
      phone: "",
      notes: "Extra achar with momo",
      items: [
        { itemId: "hb-chiya", name: "Masala Chiya", qty: 2, unitPrice: 80 },
        { itemId: "hb-momo", name: "Chicken Momo (10 pcs)", qty: 1, unitPrice: 250 },
      ],
      subtotal: 410,
      tax: 53.3,
      tax_name: "VAT",
      total: 463.3,
      status: "new",
      estimated_wait: 15,
      confirm_code: "6190",
      dining_option: "dine_in",
      created_at: now - 5 * 60000,
      updated_at: now - 5 * 60000,
    },
  ],
};


module.exports = { velvetBean, spiceLane, himalayanBeans };

